server:
  port: 9090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jrshelton/configServer
          search-paths: solstice-ecommerce-cqrs-account-rest-api
